services:
  rsync-jail:
    image: ghcr.io/kristianvld/rsync-jail:latest
    ports:
      - "2222:22"
    environment:
      - DEBUG=1
      - SFTP=1
    volumes:
      - ./ssh-keys:/etc/ssh/ssh_host_keys/         # Volume for persistent SSH host keys
      - ./users.json:/users.json:ro                # User definitions file
      - ./client1-data:/home/client1/jail/data:ro  # Read only data directory for client1
      - ./client2-data:/home/client2/jail/data     # Read-write data directory for client2
      - ./client3-data:/home/client3/jail/data     # Read-write data directory for client3
      - ./client4-data:/home/client4/jail/data     # Read-write data directory for client4
    restart: unless-stopped
    networks:
      - none
